# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "wegtam/db-tester"
  config.vm.network :forwarded_port, guest: 5432, host: 5432
  config.vm.provision "shell",
      inline: "su vagrant -c 'psql postgresql://pgtester:pgtester@localhost/postgres -c \"create database pace with owner=pgtester;\"'"
end
